[package]
name = "use-change-event"
description = "Change-event and stream-event primitives for RustUse"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
documentation = "https://docs.rs/use-change-event"
keywords = ["nosql", "change", "event", "stream"]
categories = ["database", "data-structures", "development-tools"]

[lints]
workspace = true
